TeamBruceCampbell/team-grace-shopper

server/db/models/author.js
server/db/models/genre.js
server/db/models/product.js

created author, genre, fixed product model

---

client/components/main.js
client/components/navbar.js
package-lock.json
package.json
public/index.html

- installed Semantic UI and added to HTML head
- Created Navbar component and coded basic outline

Semanticui and navbar outline

---

package.json
server/db/db.js
server/db/models/index.js
server/db/models/lineItems.js
server/db/models/order.js
server/db/models/review.js
server/db/models/review.spec.js
server/db/models/user.js

updated models

---

client/components/main.js
client/components/navbar.js
client/components/sidebar.js

add sidebar and apply semantic grid to two columns for sidebar and main

---

client/routes.js

adds product and single product routes

---

client/components/navbar.js
client/components/sidebar.js
public/style.css

update sidebar with mock home, products, and cart buttons

---

server/db/models/address.js
server/db/models/address.spec.js
server/db/models/index.js
server/db/models/lineItems.js
server/db/models/order.js
server/db/models/product.js
server/db/models/review.js
server/db/models/review.spec.js

added  author model with test,
changed Sequelize.NUMBER to Sequelize.DECIMAL,
changed default stockQuantity to 0 on product model,
fixed review spec

Author model

---

client/components/SingleGenre.jsx
client/components/SingleProduct.jsx

creates singlegenre component

---

client/components/Products.jsx
client/components/index.js
client/components/main.js
client/routes.js

Hello World
from localhost/8080/products

creates products.jsx

---

server/db/models/product.js
server/db/models/product.spec.js
server/db/models/review.spec.js

changed review model a bit and product, and wrote the product spec, which it passes

Product spec

---

server/db/index.js
server/db/models/index.js
server/db/models/order.js
server/index.js

associations done

---

server/api/users.spec.js
server/db/models/address.spec.js
server/db/models/product.spec.js
server/db/models/review.spec.js
server/db/models/user.spec.js

fixed tests

---

client/components/main.js
public/index.html
public/style.css

simple update to change html title from boilermaker to graceshopper

changed html title to graceShopper

---

client/components/AdminDashboard.jsx

created adminDashboard.jsx

---

client/components/cart.js
client/components/main.js
client/components/navbar.js
client/components/sidebar.js
client/reducers/index.js

making uppercase

---

client/components/ConfirmOrderInfo.js
client/components/index.js

create info confirm for order component

---

client/components/OrderConfirmation.js

creates orderconfirmation

---

server/api/books.js
server/api/index.js

set up get all books route

---

client/components/AdminDashboard.js
client/components/AdminOrdersList.js

admin all orders component made

---

client/components/Sidebar.js
client/components/UserAccountDashboard.js
client/components/index.js
client/routes.js

add user account component and updated sidebar and routes to access it

---

client/reducers/ProductReducer.js

refactor getallbooks reducer, thunk, and action creators

---

client/components/FeaturedProducts.js
client/components/Main.js
client/components/Products.js
client/components/UserHome.js
client/reducers/ProductReducer.js
client/reducers/index.js
client/routes.js
client/store/index.js
client/store/products.js
script/seed.js
server/api/books.js

rendered products with images and desc

---

server/api/genres.js
server/api/index.js

genres route

---

client/components/BookCard.js
client/components/FeaturedProducts.js
client/components/Products.js

creates bookcard component

---

client/index.js
package-lock.json
package.json

fix test error and now can test

---

client/components/Navbar.js
client/components/Sidebar.js
client/components/UserHome.js
client/routes.js
public/style.css

changed ui button names, added bg color, and fixed auto display to home

---

client/components/Cart.js
server/api/index.js
server/api/orders.js
server/db/models/index.js

some routes, especially for cart functions

---

client/routes.js
client/store/cart.js
client/store/index.js
server/api/orders.js

getCart frontend

---

client/components/BookCard.js
client/components/Products.js
public/style.css

update all books ui to evenly display

---

server/api/orders.js

cart includes full lineItems

---

client/components/Cart.js

user boolean works and renders

---

client/components/Products.js
client/components/Products.spec.js
client/components/UserHome.spec.js

create products test

---

client/routes.js

No longer loading books in routes

not loading books on top

---

client/components/BookCard.spec.js
client/components/Products.js
client/components/Products.spec.js
client/components/UserHome.js
client/components/UserHome.spec.js

creates bookcardtest

---

client/components/Cart.js
client/routes.js
server/api/orders.js

cart Component

---

client/components/Navbar.js
server/api/orders.js
server/api/users.js
server/db/models/index.js

Unauthorized

---

client/components/AdminOrdersList.js
client/components/OrderFilterType.js
client/store/adminAllOrders.js
server/api/orders.js

fix up ui for admin dropdown filter

---

client/components/BookCard.spec.js
client/components/FeaturedProducts.js
client/components/FeaturedProducts.spec.js

renders features

---

client/components/AdminAllUsers.js
client/components/AdminDashboard.js
client/store/adminAllOrders.js
client/store/adminAllUsers.js
client/store/index.js
server/api/users.js

add api for all users for admin

---

script/seed.js

adds one book as test

---

client/components/AdminAllUsers.js
client/components/AdminOrdersList.js
client/components/AdminViewAllUsers.js
client/components/OrderFilterType.js
client/store/adminAllOrders.js
client/store/adminAllUsers.js

admin view all users and table created for ui display

---

client/components/Cart.js
client/components/Navbar.js
client/store/cart.js
server/api/orders.js

changed cart in store

---

client/components/BookCard.js
server/api/orders.js

change orderQuantity strategy

---

client/components/SingleGenre.js
client/routes.js
client/store/singleGenre.js
script/seed.js

creates allgenres and added to seed file

---

client/components/Navbar.js

navbar responds to user status

---

client/components/AdminAllUsers.js
client/components/UserOrders.js
client/store/index.js
client/store/userOrders.js
server/api/orders.js

create user previous orders api and display ui

---

server/api/orders.js

Added put('/checkout') to orders api route

Checkout api

---

client/components/UserOrders.js
client/components/UserReviews.js
client/store/index.js
client/store/userReviews.js
server/api/index.js
server/api/reviews.js

api route for user reviews and ui update to display users reviews

---

server/api/orders.js

fixed checkout and delete

---

server/api/orders.js

fixed orders again

---

client/components/AdminViewAllUsers.js
client/components/BookCard.js
client/components/OrderFilterType.js
client/store/adminAllUsers.js
server/api/users.js

admin can delete users and change admin status in one view

---

client/components/Navbar.js
client/components/SingleGenre.js
client/components/SingleProduct.js
client/routes.js
client/store/index.js
client/store/singleGenre.js
public/style.css
script/seed.js

adds genre and book titles to singlegenre

---

client/components/AuthForm.js
client/components/BookCard.js
client/components/Cart.js
client/components/Main.js
client/components/UserHome.js
client/routes.js
client/store/cart.js
client/store/user.js
server/api/orders.js

authorized and unauthorized both users can maintain their cart

stable cart

---

client/components/Navbar.js
client/components/UserHome.js
client/components/UserOrders.js
client/components/UserReviews.js
server/api/books.js

add item details to user reviews and previous orders

---

client/components/ReviewInput.js
client/components/SingleProductReviews.js

changed some stuff

---

client/components/Cart.js
client/components/ConfirmOrderInfo.js
client/components/index.js
client/routes.js
client/store/cart.js
client/store/currentOrder.js
client/store/userOrders.js
server/api/orders.js

updated cart

---

server/index.js

#146 
I think we have to all manually copy and paste the google id and key to your secrets.js file.  I can slack this out if needed

part 1 of googleauth, added googleID to auth path

---

client/components/SingleGenre.js

makes single genre work and pretty

---

client/components/Navbar.js
public/style.css

moves navbar left

---

client/components/Cart.js
client/components/Signup.js
client/components/index.js
client/store/cart.js
client/store/user.js
server/auth/index.js

signupAddress

---

client/components/BookCard.js
client/components/BookCard.spec.js
client/components/FeaturedProducts.js
client/components/FeaturedProducts.spec.js
client/components/OrderFilterType.js
client/components/OrderFilterType.spec.js
server/api/admin.js

add filteredOrder component tests and update other tests

---

client/components/Cart.js
client/components/SingleProduct.js
client/store/index.js
client/store/sendEmail.js
package-lock.json
package.json
public/style.css
script/seed.js
server/api/orders.js
server/index.js

creates send email functionality and adds to seed

---

client/components/AuthForm.js

fixed login

---

client/components/Sidebar.js
client/routes.js
client/store/genres.js
client/store/index.js

genres dropdown

---

client/components/AddressForm.js
client/components/Cart.js
client/components/ConfirmOrderInfo.js
client/store/currentOrder.js
client/store/sendEmail.js
server/api/orders.js
server/auth/index.js

After placing an order user will receive email

email done

---

client/components/AuthForm.js
client/components/ReviewInput.js
client/components/Sidebar.js
server/api/orders.js

fixed a ton of stuff

---

client/components/Sidebar.js

genre icon

---

client/components/AdminCreateNewBook.js
client/components/AdminDashboard.js
client/components/AdminNewBookForm.js
client/store/products.js
server/api/admin.js

admin can create new book
